### ISSUE TITLE
Unable to destroy blocks

### ISSUE THREAD

**Issue by Ree-jp** [WaterdogPE/WaterdogPE#169]
Blocks can be destroyed or not.

# reproduction

1, disable use_fast_codec
2, Destroy the block while looking down

## version
WaterdogPE 1.1.6
java 16

## Error code

[DEBUG] Error occurred whilst decoding packet
com.nukkitx.protocol.bedrock.exception.PacketSerializeException: Error whilst deserializing PlayerAuthInputPacket(rotation=(88.793915, -178.56969, -178.56969), position=(249.39235, 9.392979, 259.44922), motion=(0.0, 0.0), inputData=[PERFORM_ITEM_INTERACTION, PERFORM_BLOCK_ACTIONS], inputMode=MOUSE, playMode=SCREEN, vrGazeDirection=null, tick=21020, delta=(0.0, 4.4570738E-4, -0.0), itemUseTransaction=ItemUseTransaction(legacyRequestId=0, legacySlots=[], usingNetIds=false, actions=[], actionType=2, blockPosition=(249, 5, 259), blockFace=1, hotbarSlot=4, itemInHand=ItemData(id=0, damage=0, count=0, tag=null, canPlace=[], canBreak=[], blockingTicks=0, blockRuntimeId=0, usingNetId=false, netId=0), playerPosition=(249.39235, 9.392236, 259.44922), clickPosition=(0.0, 0.0, 0.0), blockRuntimeId=0), itemStackRequest=null, playerActions=[PlayerBlockActionData(action=START_BREAK, blockPosition=(249, 5, 259), face=1), PlayerBlockActionData(action=STOP_BREAK, blockPosition=(18, 249, 5), face=259)])

<details>
<summary>trace</summary>

 at com.nukkitx.protocol.bedrock.BedrockPacketCodec.tryDecode(BedrockPacketCodec.java:66) ~[server.jar:?]
        at com.nukkitx.protocol.bedrock.wrapper.BedrockWrapperSerializerV9_10.deserialize(BedrockWrapperSerializerV9_10.java:74) ~[server.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:283) ~[server.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.lambda$onEncapsulated$0(BedrockRakNetSessionListener.java:39) ~[server.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[server.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[server.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[server.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[server.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(109) + length(1) exceeds writerIndex(109): UnpooledSlicedByteBuf(ridx: 109, widx: 109, cap: 109/109, unwrapped: PooledUnsafeDirectByteBuf(ridx: 130, widx: 130, cap: 8192))
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[server.jar:?]
        at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730) ~[server.jar:?]
        at com.nukkitx.network.VarInts.decode(VarInts.java:46) ~[server.jar:?]
        at com.nukkitx.network.VarInts.readInt(VarInts.java:14) ~[server.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockPacketHelper.readVector3i(BedrockPacketHelper.java:359) ~[server.jar:?]
        at com.nukkitx.protocol.bedrock.v428.serializer.PlayerAuthInputSerializer_v428.readPlayerBlockActionData(PlayerAuthInputSerializer_v428.java:126) ~[server.jar:?]
        at com.nukkitx.protocol.bedrock.v431.serializer.PlayerAuthInputSerializer_v431.readPlayerBlockActionData(PlayerAuthInputSerializer_v431.java:28) ~[server.jar:?]
        at com.nukkitx.protocol.bedrock.v428.serializer.PlayerAuthInputSerializer_v428.deserialize(PlayerAuthInputSerializer_v428.java:99) ~[server.jar:?]
        at com.nukkitx.protocol.bedrock.v428.serializer.PlayerAuthInputSerializer_v428.deserialize(PlayerAuthInputSerializer_v428.java:17) ~[server.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockPacketCodec.tryDecode(BedrockPacketCodec.java:64) ~[server.jar:?]
        ... 9 more
</details

https://user-images.githubusercontent.com/49682119/160448844-2300950a-0759-478d-ad34-9f9c61e5c4b8.mp4

**Comment by Alemiz112** [comment]
Hi, is this bug still happening?

**Comment by Ree-jp** [comment]
Thank you for fixing the bug
