### ISSUE TITLE
An error occurred while the player was connecting to WaterdogPE

### ISSUE THREAD

**Issue by Pigeon2333** [WaterdogPE/WaterdogPE#175]
I have debug mode enabled and here is the server log:
[server.zip](https://github.com/WaterdogPE/WaterdogPE/files/8721779/server.zip)
WaterdogPE's console has the following error when the player(Client version 1.18.30, protocol version 503) joins the server:
`2022-05-19 08:46:11.239 [RakNet Listener - #5] DEBUG - [/192.168.0.102:64532] <-> Received first data
2022-05-19 08:46:11.551 [Bedrock Listener - #1] INFO  - [/192.168.0.102:64532|wotmcall1103563] <-> Upstream has connected (protocol=503)
2022-05-19 08:46:27.082 [RakNet Listener - #31] DEBUG - [/192.168.0.102:64532|wotmcall1103563] Unable to connect to downstream lobby1
java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?]
	at com.nukkitx.network.raknet.RakNetClient.onTick(RakNetClient.java:121) ~[proxy.jar:?]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[proxy.jar:?]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:176) ~[proxy.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[proxy.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[proxy.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[proxy.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[proxy.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[proxy.jar:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.util.concurrent.TimeoutException
	... 9 more
2022-05-19 08:46:27.091 [RakNet Listener - #31] INFO  - [/192.168.0.102:64532|wotmcall1103563] -> Upstream has disconnected
2022-05-19 08:46:27.091 [RakNet Listener - #31] INFO  - [wotmcall1103563] -> Disconnected with: §cConnection to lobby1 failed: java.util.concurrent.TimeoutException`
I confirm that all the downstream servers are online, and I get the correct output when I execute "wdlist".BTW,my lobby server's console doesn't have any output.

**Comment by TobiasGrether** [comment]
Please check out our documentation on this [here](https://docs.waterdog.dev/link/25#bkmrk-java.util.concurrent).
