### ISSUE TITLE
Error occurred whilst decoding PlayerAuthInputPacket

### ISSUE THREAD

**Issue by Ree-jp** [WaterdogPE/WaterdogPE#184]
Some playerAuthInputPackets may not be able to decode and block may not be destroyed

# reproduction
1, disable use_fast_codec
2, join server

# version
Software Version: 1.1.8
Build Version: 160
Development Build: true
Discovered branch master commitId a99f392

# Error code
[DEBUG] Error occurred whilst decoding packet
com.nukkitx.protocol.bedrock.exception.PacketSerializeException: Error whilst deserializing PlayerAuthInputPacket(rotation=(0.5426636, -165.84613, -165.84613), position=(275.42603, 49.62001, 242.45294), motion=(0.0, 0.0), inputData=[], inputMode=MOUSE, playMode=SCREEN, inputInteractionModel=null, vrGazeDirection=null, tick=0, delta=null, itemUseTransaction=null, itemStackRequest=null, playerActions=[])

<details>
<summary>trace</summary>
        at com.nukkitx.protocol.bedrock.BedrockPacketCodec.tryDecode(BedrockPacketCodec.java:66) ~[server.jar:?]
        at com.nukkitx.protocol.bedrock.wrapper.BedrockWrapperSerializerV9_10.deserialize(BedrockWrapperSerializerV9_10.java:74) ~[server.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:283) ~[server.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.lambda$onEncapsulated$0(BedrockRakNetSessionListener.java:39) ~[server.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[server.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[server.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[server.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[server.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException
</details>

**Comment by Alemiz112** [comment]
Hi, thanks for bug report. I will have a look into this soon! However, I recommend you to enable fast codec in order to improve performance.

**Comment by TobiasGrether** [comment]
Resolved here: https://github.com/CloudburstMC/Protocol/commit/6053e5a1c8c1c6dd226dbac42d25ced9dcdb9c02
