### ISSUE TITLE
Packet ID does not exist.

### ISSUE THREAD

**Issue by Cosmic5173** [WaterdogPE/WaterdogPE#186]
When a packet is sent to the player, an exception is thrown saying the packet id does not exist.

``` java
var pk = new ModalFormRequestPacket();
pk.setFormId(FormHandler.nextFormId());
pk.setFormData(form.toJson());
player.sendPacket(pk);
```

```FormRequestPacket does not exist.
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalArgumentException: Packet ID for com.nukkitx.protocol.bedrock.packet.ModalFormRequestPacket does not exist.
        at com.nukkitx.protocol.bedrock.BedrockPacketCodec.getId(BedrockPacketCodec.java:116) ~[server.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockPacketCodec.getId(BedrockPacketCodec.java:110) ~[server.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockSession.checkPacket(BedrockSession.java:114) ~[server.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockSession.sendPacket(BedrockSession.java:92) ~[server.jar:?]
        at dev.waterdog.waterdogpe.player.ProxiedPlayer.sendPacket(ProxiedPlayer.java:356) ~[server.jar:?]
        at net.skywarpedmc.proxycore.player.ProxyPlayer.sendForm(ProxyPlayer.java:22) ~[?:?]
        at net.skywarpedmc.proxycore.event.EventListener.onInitialServerConnectedEvent(EventListener.java:28) ~[?:?]
        at dev.waterdog.waterdogpe.event.EventHandler.handlePriority(EventHandler.java:99) ~[server.jar:?]
        at dev.waterdog.waterdogpe.event.EventHandler.lambda$handle$0(EventHandler.java:57) ~[server.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 3 more
```

**Comment by Alemiz112** [comment]
If you have enabled fast-codec in proxy config, only required packets are registered.  You can listen for `ProtocolCodecRegisterEvent` to do register extra packets.
