### ISSUE TITLE
Crash in WDPE 1.1.10

### ISSUE THREAD

**Issue by Crasher508** [WaterdogPE/WaterdogPE#210]
2022-08-09 19:11:42.912 [RakNet Listener - #3] ERROR [RakNetClient] - An exception occurred in RakNet Client, address=/0.0.0.0:0
java.lang.NoSuchMethodError: 'void com.nukkitx.protocol.bedrock.BedrockPacketHelper.readArray(io.netty.buffer.ByteBuf, java.util.Collection, java.util.function.ToIntFunction, java.util.function.BiFunction)'
	at com.nukkitx.protocol.bedrock.v448.serializer.ResourcePacksInfoSerializer_v448.deserialize(ResourcePacksInfoSerializer_v448.java:29) ~[Waterdog.jar:?]
	at com.nukkitx.protocol.bedrock.v448.serializer.ResourcePacksInfoSerializer_v448.deserialize(ResourcePacksInfoSerializer_v448.java:10) ~[Waterdog.jar:?]
	at com.nukkitx.protocol.bedrock.BedrockPacketSerializer.deserialize(BedrockPacketSerializer.java:21) ~[Waterdog.jar:?]
	at com.nukkitx.protocol.bedrock.BedrockPacketCodec.tryDecode(BedrockPacketCodec.java:64) ~[Waterdog.jar:?]
	at com.nukkitx.protocol.bedrock.wrapper.BedrockWrapperSerializerV9_10.deserialize(BedrockWrapperSerializerV9_10.java:74) ~[Waterdog.jar:?]
	at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:283) ~[Waterdog.jar:?]
	at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.onEncapsulated(BedrockRakNetSessionListener.java:34) ~[Waterdog.jar:?]
	at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:277) ~[Waterdog.jar:?]
	at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:403) ~[Waterdog.jar:?]
	at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:383) ~[Waterdog.jar:?]
	at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:376) ~[Waterdog.jar:?]
	at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:252) ~[Waterdog.jar:?]
	at com.nukkitx.network.raknet.pipeline.ClientMessageHandler.channelRead0(ClientMessageHandler.java:46) ~[Waterdog.jar:?]
	at com.nukkitx.network.raknet.pipeline.ClientMessageHandler.channelRead0(ClientMessageHandler.java:13) ~[Waterdog.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[Waterdog.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Waterdog.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Waterdog.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Waterdog.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[Waterdog.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Waterdog.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Waterdog.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[Waterdog.jar:?]
	at io.netty.channel.epoll.EpollDatagramChannel.processPacket(EpollDatagramChannel.java:618) ~[Waterdog.jar:?]
	at io.netty.channel.epoll.EpollDatagramChannel.recvmsg(EpollDatagramChannel.java:653) ~[Waterdog.jar:?]
	at io.netty.channel.epoll.EpollDatagramChannel.access$100(EpollDatagramChannel.java:56) ~[Waterdog.jar:?]
	at io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:492) ~[Waterdog.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[Waterdog.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[Waterdog.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[Waterdog.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[Waterdog.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
	

config.yml:

# Waterdog Main Configuration file
# Configure your desired network settings here.

...
permissions_default:
- waterdog.command.nope
enable_debug: false
upstream_encryption: true
online_mode: true
enable_ipv6: false
use_login_extras: false
replace_username_spaces: false
enable_query: true
prefer_fast_transfer: true
use_fast_codec: true
inject_proxy_commands: true
upstream_compression_level: 6
downstream_compression_level: 2
enable_edu_features: true
enable_packs: true
overwrite_client_packs: false
force_server_packs: false
pack_cache_size: 16
default_idle_threads: -1

**Comment by Alemiz112** [comment]
Make sure you are using the latest build from Jenkins.

**Comment by Crasher508** [comment]
Ok, this crash triggered by Jar from Github Release

**Comment by Alemiz112** [comment]
Should be fixed.
