### ISSUE TITLE
[BUG] java.lang.NumberFormatException: For input string: "20-testing"

### ISSUE THREAD

**Issue by alvin0319** [WaterdogPE/WaterdogPE#244]
**Describe the bug**
WaterdogPE doesn't start in the development build of Hotspot JDK due to its version semver.

```
Exception in thread "WaterdogPE-main" java.lang.NumberFormatException: For input string: "20-testing"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
        at java.base/java.lang.Integer.parseInt(Integer.java:665)
        at java.base/java.lang.Integer.parseInt(Integer.java:781)
        at dev.waterdog.waterdogpe.WaterdogPE.getJavaVersion(WaterdogPE.java:118)
        at dev.waterdog.waterdogpe.WaterdogPE.main(WaterdogPE.java:50)
```

**To Reproduce**
1. Download this version of JDK: https://builds.shipilev.net/openjdk-jdk-lilliput/openjdk-jdk-lilliput-linux-x86_64-server-release-gcc12-glibc2.34.tar.xz
2. Start server using this JDK

**Expected behavior**
Server starts normally.

**Screenshots**
N/A

**Platform Information:**
 - Game Platform: [e.g. iOS] All
 - Game (Client) Version [e.g. v1.19.30] 1.19.41
 - Server OS [e.g. Windows] Ubuntu 20.04
 - Java Version [e.g. Java 18] 20
 - Server Deployment Method [e.g. Pterodactyl, Docker] Fresh Ubuntu

**Additional context**
It isn't recommended to use the development version of java but... I want to use this... xD

**Comment by Alemiz112** [comment]
Should be fixed when #253 is merged.
