### ISSUE TITLE
[BUG] Error with encoding CameraInstructionPacket

### ISSUE THREAD

**Issue by Toper9636** [WaterdogPE/WaterdogPE#300]
**Describe the bug**
Error occurred when using [WDPE (Latest pre-release version)](https://github.com/WaterdogPE/WaterdogPE/releases/tag/latest)

When a player switches servers I send him this packet and this error occurs:

```java
19:25:26 [ERROR] Error encoding packet CameraInstructionPacket(setInstruction=null, fadeInstruction=CameraFadeInstruction(timeData=CameraFadeInstruction.TimeData(fadeInTime=0.5, waitTime=0.6, fadeOutTime=0.5), color=java.awt.Color[r=0,g=0,b=60]), clear=OptionalBoolean.empty)
java.lang.NullPointerException: Cannot invoke "org.cloudburstmc.protocol.bedrock.codec.BedrockPacketDefinition.getId()" because the return value of "org.cloudburstmc.protocol.bedrock.codec.BedrockCodec.getPacketDefinition(java.lang.Class)" is null
        at dev.waterdog.waterdogpe.network.connection.codec.packet.BedrockPacketCodec.getPacketId(BedrockPacketCodec.java:143) ~[server.jar:?]        at dev.waterdog.waterdogpe.network.connection.codec.packet.BedrockPacketCodec.encode(BedrockPacketCodec.java:86) ~[server.jar:?]
        at dev.waterdog.waterdogpe.network.connection.codec.packet.BedrockPacketCodec.encode(BedrockPacketCodec.java:58) ~[server.jar:?]
        at dev.waterdog.waterdogpe.network.connection.codec.packet.BedrockPacketCodec.encode(BedrockPacketCodec.java:36) ~[server.jar:?]
        at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[server.jar:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[server.jar:?]
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984) ~[server.jar:?]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[server.jar:?]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[server.jar:?]
        at dev.waterdog.waterdogpe.network.connection.peer.ProxiedBedrockPeer.onTick(ProxiedBedrockPeer.java:106) ~[server.jar:?]
        at dev.waterdog.waterdogpe.network.connection.peer.ProxiedBedrockPeer.sendPacket0(ProxiedBedrockPeer.java:126) ~[server.jar:?]
        at dev.waterdog.waterdogpe.network.connection.peer.ProxiedBedrockPeer.lambda$sendPacket$0(ProxiedBedrockPeer.java:114) ~[server.jar:?]        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[server.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[server.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[server.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[server.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[server.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:?]
        at java.lang.Thread.run(Thread.java:842) [?:?]
```

**To Reproduce**
I listened to the ServerTransferEvent event and wrote this code there:
```java
CameraInstructionPacket pk = new CameraInstructionPacket();
pk.setFadeInstruction(new CameraFadeInstruction(
    new CameraFadeInstruction.TimeData(0.5f, 0.6f, 0.5f),
    new Color(0, 0, 0.2352941334247589f)
));

event.getPlayer().sendPacket(pk);
```

**Expected behavior**
**I WAS EXPECTING THE PACKAGE TO GO OUT**

**Platform Information:**
 - Game Platform: Win10
 - Game (Client) Version: 1.20.51
 - Server OS: Windows
 - Java Version: 17
 - Server Deployment Method: none

**Comment by Toper9636** [comment]
?????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????

**Comment by belohnung** [comment]
needs more question marks

**Comment by belohnung** [comment]
My guess is that the Codec Waterdog uses does not include this packet since its not needed for normal operation, you could extend their Codec and add it on your own, beware that this packet probably does not exist in every version that waterdog supports

**Comment by Toper9636** [comment]
WDPE uses [this library](https://github.com/CloudburstMC/Protocol) to encode and decode packets, they don't need to add anything to support packets

**Comment by belohnung** [comment]
Last time i worked with WaterdogPE, they constructed their own Codecs (using the codec system of the library you linked) which only contained Packets needed for Waterdog stuff

**Comment by Alemiz112** [comment]
Hi, yes, this is correct. We do only register packets that are required by the proxy itself. If plugin needs to use another packet, it must be registered by that plugin. Use [this](https://github.com/WaterdogPE/WaterdogPE/blob/master/src/main/java/dev/waterdog/waterdogpe/network/protocol/ProtocolCodecs.java#L123) API method as reference.
