### ISSUE TITLE
[BUG] This is a bug!

### ISSUE THREAD

**Issue by HerrSchnecki** [WaterdogPE/WaterdogPE#310]
**Describe the bug**
If you run, for example, /navigator and the command opens a UI, and then you close the UI again, you will be kicked out.

**Error**
io.netty.channel.ConnectTimeoutException: null
	at org.cloudburstmc.netty.handler.codec.raknet.client.RakClientOfflineHandler.onTimeout(RakClientOfflineHandler.java:90) ~[Waterdog.jar:?]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[Waterdog.jar:?]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153) ~[Waterdog.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[Waterdog.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[Waterdog.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[Waterdog.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[Waterdog.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[Waterdog.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[Waterdog.jar:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]

**Comment by xxAROX** [comment]
Look into the console of your downstream server

**Comment by HerrSchnecki** [comment]
There are no errors in the console of the downstream server.
