### ISSUE TITLE
The server hub went down, reason: Error whilst deserializing PlayerListPacketCentries=[], action=ADD)

### ISSUE THREAD

**Issue by Odidak1** [WaterdogPE/WaterdogPE#312]
The server hub went down, reason: Error whilst deserializing PlayerListPacketCentries=[], action=ADD)

**Comment by MLCraftKaiKai** [comment]
Please use custom skin (skin. png), market skin cannot be accessed

**Comment by Odidak1** [comment]
But when I was still using version 1.20.80 there were no crashes

Pada Sab, 15 Jun 2024 17.15, MagicaIP ***@***.***> menulis:

**Comment by MLCraftKaiKai** [comment]
Maybe this is a version feature, I don't know the specific reason :\

**Comment by Odidak1** [comment]
I have used the regular skin but it still crashes, please check and fix it

Pada Sab, 15 Jun 2024 17.27, MagicaIP ***@***.***> menulis:

**Comment by Alemiz112** [comment]
Hi, can you please provide full error?

**Comment by Odidak1** [comment]
Pada Min, 16 Jun 2024 23.33, Alemiz ***@***.***> menulis:

**Comment by Odidak1** [comment]
2024-06-16 15:35:54.010 [WaterdogPE-main] INFO  - §bStarting WaterDogPE
proxy software!
2024-06-16 15:35:54.012 [WaterdogPE-main] INFO  - §3Software Version: 2.0.2
2024-06-16 15:35:54.012 [WaterdogPE-main] INFO  - §3Build Version: #build
2024-06-16 15:35:54.012 [WaterdogPE-main] INFO  - §3Development Build: true
2024-06-16 15:35:54.012 [WaterdogPE-main] INFO  - §3Software Authors:
WaterdogTEAM
2024-06-16 15:35:54.012 [WaterdogPE-main] INFO  - §3Latest Supported Game
Version: 1.21.0
2024-06-16 15:35:54.012 [WaterdogPE-main] WARN  - Custom build? Unofficial
builds should be not run in production!
2024-06-16 15:35:54.015 [WaterdogPE-main] INFO  - §eUsing memory leak
detection level: SIMPLE
2024-06-16 15:36:01.513 [WaterdogPE-main] INFO  - Anonymous error reporting
is enabled.
2024-06-16 15:36:01.600 [WaterdogPE-main] INFO  - Using EPOLL channel
implementation as default!
2024-06-16 15:36:01.718 [WaterdogPE-main] INFO  - Using fast codec for
improved performance and stability!
2024-06-16 15:36:01.735 [WaterdogPE-main] INFO  - Loading resource packs!
2024-06-16 15:36:01.904 [WaterdogPE-main] INFO  - Loaded 5 packs!
2024-06-16 15:36:01.904 [WaterdogPE-main] INFO  - Binding to /0.0.0.0:19132
2024-06-16 15:36:02.103 [WaterdogPE-main] INFO  - Started query on address /
0.0.0.0:19132
2024-06-16 15:36:54.190 [Bedrock Listener - #0] INFO  -
[/114.124.148.150:33626|Odidak] <-> Upstream has connected (protocol=685
version=1.21.0)
2024-06-16 15:36:54.386 [Bedrock Listener - #0] INFO  - Encryption enabled
for /114.124.148.150:33626
2024-06-16 15:36:55.873 [Bedrock Listener - #1] INFO  - [
play.saungmc.my.id/143.110.241.233:19133|Odidak] -> Downstream [hub] has
connected
2024-06-16 15:36:56.430 [Bedrock Listener - #1] INFO  - Encryption enabled
for play.saungmc.my.id/143.110.241.233:19133
2024-06-16 15:37:06.999 [Bedrock Listener - #1] WARN  - Failed to decode
packet
org.cloudburstmc.protocol.bedrock.codec.PacketSerializeException: Error
whilst deserializing PlayerListPacket(entries=[], action=ADD)
at
org.cloudburstmc.protocol.bedrock.codec.BedrockCodec.tryDecode(BedrockCodec.java:70)
~[server.jar:?]
at
dev.waterdog.waterdogpe.network.protocol.handler.ProxyBatchBridge.decodePacket(ProxyBatchBridge.java:92)
~[server.jar:?]
at
dev.waterdog.waterdogpe.network.protocol.handler.ProxyBatchBridge.onBedrockBatch(ProxyBatchBridge.java:56)
~[server.jar:?]
at
dev.waterdog.waterdogpe.network.connection.client.BedrockClientConnection.channelRead0(BedrockClientConnection.java:87)
~[server.jar:?]
at
dev.waterdog.waterdogpe.network.connection.client.BedrockClientConnection.channelRead0(BedrockClientConnection.java:57)
~[server.jar:?]
at
io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
~[server.jar:?]
at
io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
~[server.jar:?]
at
io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
~[server.jar:?]
at
io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
~[server.jar:?]
at
io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
~[server.jar:?]
at
io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
~[server.jar:?]
at
io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
~[server.jar:?]
at
io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
~[server.jar:?]
at
io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
~[server.jar:?]
at
io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
~[server.jar:?]
at
io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
~[server.jar:?]
at
org.cloudburstmc.netty.handler.codec.raknet.ProxyInboundRouter.channelRead(ProxyInboundRouter.java:66)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
~[server.jar:?]
at
org.cloudburstmc.netty.handler.codec.raknet.common.EncapsulatedToMessageHandler.channelRead0(EncapsulatedToMessageHandler.java:15)
~[server.jar:?]
at
org.cloudburstmc.netty.handler.codec.raknet.common.EncapsulatedToMessageHandler.channelRead0(EncapsulatedToMessageHandler.java:8)
~[server.jar:?]
at
io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
~[server.jar:?]
at
org.cloudburstmc.netty.handler.codec.raknet.AdvancedChannelInboundHandler.channelRead(AdvancedChannelInboundHandler.java:48)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
~[server.jar:?]
at
org.cloudburstmc.netty.handler.codec.raknet.AdvancedChannelInboundHandler.channelRead(AdvancedChannelInboundHandler.java:48)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
~[server.jar:?]
at
org.cloudburstmc.netty.handler.codec.raknet.AdvancedChannelInboundHandler.channelRead(AdvancedChannelInboundHandler.java:48)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
~[server.jar:?]
at
org.cloudburstmc.netty.handler.codec.raknet.common.RakSessionCodec.onOrderedReceived(RakSessionCodec.java:353)
~[server.jar:?]
at
org.cloudburstmc.netty.handler.codec.raknet.common.RakSessionCodec.checkForOrdered(RakSessionCodec.java:334)
~[server.jar:?]
at
org.cloudburstmc.netty.handler.codec.raknet.common.RakSessionCodec.handleDatagram(RakSessionCodec.java:322)
~[server.jar:?]
at
org.cloudburstmc.netty.handler.codec.raknet.common.RakSessionCodec.channelRead(RakSessionCodec.java:218)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
~[server.jar:?]
at
io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:102)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
~[server.jar:?]
at
io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
~[server.jar:?]
at
io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
~[server.jar:?]
at
org.cloudburstmc.netty.handler.codec.raknet.AdvancedChannelInboundHandler.channelRead(AdvancedChannelInboundHandler.java:48)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
~[server.jar:?]
at
org.cloudburstmc.netty.handler.codec.raknet.client.RakClientProxyRouteHandler.channelRead(RakClientProxyRouteHandler.java:50)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
~[server.jar:?]
at
io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
~[server.jar:?]
at
io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
~[server.jar:?]
at
io.netty.channel.epoll.EpollDatagramChannel.connectedRead(EpollDatagramChannel.java:606)
~[server.jar:?]
at
io.netty.channel.epoll.EpollDatagramChannel.access$400(EpollDatagramChannel.java:56)
~[server.jar:?]
at
io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:538)
~[server.jar:?]
at
io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:425)
~[server.jar:?]
at
io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
~[server.jar:?]
at
io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
~[server.jar:?]
at
io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
~[server.jar:?]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
~[server.jar:?]
at
io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
~[server.jar:?]
at
io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
~[server.jar:?]
at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.IllegalArgumentException: Tried to read 273203 bytes
but maximum is 262144
at
org.cloudburstmc.protocol.common.util.Preconditions.checkArgument(Preconditions.java:291)
~[server.jar:?]
at
org.cloudburstmc.protocol.bedrock.codec.BaseBedrockCodecHelper.readStringMaxLen(BaseBedrockCodecHelper.java:118)
~[server.jar:?]
at
org.cloudburstmc.protocol.bedrock.codec.v568.BedrockCodecHelper_v568.readSkin(BedrockCodecHelper_v568.java:35)
~[server.jar:?]
at
org.cloudburstmc.protocol.bedrock.codec.v390.serializer.PlayerListSerializer_v390.readEntryBase(PlayerListSerializer_v390.java:79)
~[server.jar:?]
at
org.cloudburstmc.protocol.bedrock.codec.v649.serializer.PlayerListSerializer_v649.readEntryBase(PlayerListSerializer_v649.java:22)
~[server.jar:?]
at
org.cloudburstmc.protocol.bedrock.codec.v390.serializer.PlayerListSerializer_v390.deserialize(PlayerListSerializer_v390.java:46)
~[server.jar:?]
at
org.cloudburstmc.protocol.bedrock.codec.v390.serializer.PlayerListSerializer_v390.deserialize(PlayerListSerializer_v390.java:14)
~[server.jar:?]
at
org.cloudburstmc.protocol.bedrock.codec.BedrockCodec.tryDecode(BedrockCodec.java:68)
~[server.jar:?]
... 96 more
2024-06-16 15:37:06.999 [Bedrock Listener - #1] WARN  - [
play.saungmc.my.id/143.110.241.233:19133|Odidak] - exception caught
org.cloudburstmc.protocol.bedrock.codec.PacketSerializeException: Error
whilst deserializing PlayerListPacket(entries=[], action=ADD)
at
org.cloudburstmc.protocol.bedrock.codec.BedrockCodec.tryDecode(BedrockCodec.java:70)
~[server.jar:?]
at
dev.waterdog.waterdogpe.network.protocol.handler.ProxyBatchBridge.decodePacket(ProxyBatchBridge.java:92)
~[server.jar:?]
at
dev.waterdog.waterdogpe.network.protocol.handler.ProxyBatchBridge.onBedrockBatch(ProxyBatchBridge.java:56)
~[server.jar:?]
at
dev.waterdog.waterdogpe.network.connection.client.BedrockClientConnection.channelRead0(BedrockClientConnection.java:87)
~[server.jar:?]
at
dev.waterdog.waterdogpe.network.connection.client.BedrockClientConnection.channelRead0(BedrockClientConnection.java:57)
~[server.jar:?]
at
io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
~[server.jar:?]
at
io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
~[server.jar:?]
at
io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
~[server.jar:?]
at
io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
~[server.jar:?]
at
io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
~[server.jar:?]
at
io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
~[server.jar:?]
at
io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
~[server.jar:?]
at
io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
~[server.jar:?]
at
io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
~[server.jar:?]
at
io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
~[server.jar:?]
at
io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
~[server.jar:?]
at
org.cloudburstmc.netty.handler.codec.raknet.ProxyInboundRouter.channelRead(ProxyInboundRouter.java:66)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
~[server.jar:?]
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:

Pada Sen, 17 Jun 2024 06.18, Radit Maulana ***@***.***> menulis:

**Comment by irrld** [comment]
This issue happens when the client sends a geometry data bigger than 256kb, protocol library limits the read of such geometry data. Using a different skin (a non skin creator/persona) would solve your issues. 

In the future, we might add an option to allow higher geometry limits.
