### ISSUE TITLE
Nukkit Protocol Lib

### ISSUE THREAD

**Issue by xxAROX** [WaterdogPE/WaterdogPE#35]
**Describe the bug**
Joining doesn't work

**To Reproduce**
1. Join proxy
2. Wait
3. You can see the server map, but you can't move

**Expected behavior**
Join without freeze effect

**Screenshots**
![grafik](https://user-images.githubusercontent.com/57589973/106403366-9706a380-642e-11eb-9208-4d4a0436a6a0.png)

**Platform (please complete the following information):**
 - OS: Linux
 - Java 11
 - latest

**Comment by TobiasG-DE** [comment]
In the logs its visible that the client sent a PacketViolationWarning before disconnecting. Can you please give us the whole line so we can have a look at it?

**Comment by xxAROX** [comment]
Sure!
```log
20:08:29 [INFO ] [/95.116.120.53:63691|Aromastoffe] <-> Upstream has connected (protocol=422)
20:08:29 [INFO ] [/95.116.120.53:63691|Aromastoffe] -> Downstream [lobby-1] has connected
20:08:40 [WARN ] Received PacketViolationWarningPacket(type=MALFORMED_PACKET, severity=FINAL_WARNING, packetCauseId=117, context=)
20:08:40 [ERROR] An exception occurred in RakNet (Server)
java.lang.IllegalStateException: Connection has been closed
        at com.nukkitx.protocol.bedrock.BedrockSession.checkForClosed(BedrockSession.java:87) ~[Proxy.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockClientSession.disconnect(BedrockClientSession.java:15) ~[Proxy.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockClient.close(BedrockClient.java:48) ~[Proxy.jar:?]
        at pe.waterdog.network.session.SessionInjections.lambda$injectNewDownstream$1(SessionInjections.java:43) ~[Proxy.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockSession.close(BedrockSession.java:265) ~[Proxy.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener$Client.onDisconnect(BedrockRakNetSessionListener.java:63) ~[Proxy.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.close0(RakNetSession.java:599) ~[Proxy.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.close(RakNetSession.java:580) ~[Proxy.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.disconnect(RakNetSession.java:566) ~[Proxy.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.disconnect(RakNetSession.java:557) ~[Proxy.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockClientSession.disconnect(BedrockClientSession.java:16) ~[Proxy.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockClient.close(BedrockClient.java:48) ~[Proxy.jar:?]
        at pe.waterdog.network.session.ServerConnection.disconnect(ServerConnection.java:58) ~[Proxy.jar:?]
        at pe.waterdog.player.ProxiedPlayer.disconnect(ProxiedPlayer.java:290) ~[Proxy.jar:?]
        at pe.waterdog.player.ProxiedPlayer.disconnect(ProxiedPlayer.java:266) ~[Proxy.jar:?]
        at pe.waterdog.player.ProxiedPlayer.disconnect(ProxiedPlayer.java:250) ~[Proxy.jar:?]
        at pe.waterdog.network.session.SessionInjections.lambda$injectUpstreamHandlers$0(SessionInjections.java:35) ~[Proxy.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockSession.close(BedrockSession.java:265) ~[Proxy.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener$Server.onDisconnect(BedrockRakNetSessionListener.java:93) ~[Proxy.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.close0(RakNetSession.java:599) ~[Proxy.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.close(RakNetSession.java:580) ~[Proxy.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.onDisconnectionNotification(RakNetSession.java:833) ~[Proxy.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:261) ~[Proxy.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:391) ~[Proxy.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:371) ~[Proxy.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:364) ~[Proxy.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:240) ~[Proxy.jar:?]
        at com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler.channelRead(RakNetServer.java:316) ~[Proxy.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [Proxy.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [Proxy.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [Proxy.jar:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) [Proxy.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [Proxy.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [Proxy.jar:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) [Proxy.jar:?]
        at io.netty.channel.epoll.EpollDatagramChannel.read(EpollDatagramChannel.java:688) [Proxy.jar:?]
        at io.netty.channel.epoll.EpollDatagramChannel.access$100(EpollDatagramChannel.java:57) [Proxy.jar:?]
        at io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:507) [Proxy.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:502) [Proxy.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) [Proxy.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) [Proxy.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [Proxy.jar:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
        ```

**Comment by xxAROX** [comment]
fu*k my ip is there, nah i change it now XD

**Comment by TobiasG-DE** [comment]
You are stil using the ScriptCustomEventPacket. Using that will crash the client. Please don't use it anymore, the proxy won't catch it.

**Comment by xxAROX** [comment]
Ahh okay, thanks.
