### ISSUE TITLE
NoClassDefFoundError: pe/waterdog/plugin/Plugin

### ISSUE THREAD

**Issue by xxAROX** [WaterdogPE/WaterdogPE#42]
**Describe the bug**

**To Reproduce**
Start WaterdogPE

**Expected behavior**
Start without error

**Screenshots**
 * No screenshot here

**Platform (please complete the following information):**
 - Linux
 - Java 11
 - master -> Build 14

**Additional context**
```
05:37:42 [INFO ] Starting WaterDogPE proxy software!
05:37:42 [INFO ] Software Version: 1.0.0
05:37:42 [INFO ] Build Version: 14
05:37:42 [INFO ] Development Build: false
05:37:42 [INFO ] Software Authors: WaterdogTEAM
Exception in thread "WaterdogPE-main" java.lang.NoClassDefFoundError: pe/waterdog/plugin/Plugin
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
        at dev.waterdog.plugin.PluginClassLoader.findClass(PluginClassLoader.java:59)
        at dev.waterdog.plugin.PluginManager.getClassFromCache(PluginManager.java:183)
        at dev.waterdog.plugin.PluginClassLoader.findClass(PluginClassLoader.java:55)
        at dev.waterdog.plugin.PluginClassLoader.findClass(PluginClassLoader.java:41)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at dev.waterdog.plugin.PluginLoader.loadPluginJAR(PluginLoader.java:52)
        at dev.waterdog.plugin.PluginManager.loadPlugin(PluginManager.java:91)
        at dev.waterdog.plugin.PluginManager.lambda$loadPluginsIn$1(PluginManager.java:60)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at dev.waterdog.plugin.PluginManager.loadPluginsIn(PluginManager.java:60)
        at dev.waterdog.plugin.PluginManager.loadPluginsIn(PluginManager.java:52)
        at dev.waterdog.plugin.PluginManager.<init>(PluginManager.java:48)
        at dev.waterdog.ProxyServer.<init>(ProxyServer.java:116)
        at dev.waterdog.WaterdogPE.main(WaterdogPE.java:56)
Caused by: java.lang.ClassNotFoundException: pe.waterdog.plugin.Plugin
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at dev.waterdog.plugin.PluginClassLoader.findClass(PluginClassLoader.java:59)
        at dev.waterdog.plugin.PluginClassLoader.findClass(PluginClassLoader.java:41)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
```

**Comment by Alemiz112** [comment]
Hello, you are using incorrect package name in your plugin. Please use `dev.waterdog`, more [here](https://github.com/WaterdogPE/WaterdogPE#maven-usage).

**Comment by xxAROX** [comment]
ahh ok

**Comment by xxAROX** [comment]
i forgot the package changes 🤦‍♂️
