### ISSUE TITLE
Error on Join

### ISSUE THREAD

**Issue by BlckqFlorian** [WaterdogPE/WaterdogPE#53]
This error comes when a player joins.

java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:221) ~[?:?]
	at de.proxyutils.main.Main.login(Main.java:97) ~[?:?]
	at dev.waterdog.event.EventHandler.handlePriority(EventHandler.java:96) ~[Waterdog.jar:?]
	at dev.waterdog.event.EventHandler.lambda$handle$0(EventHandler.java:55) ~[Waterdog.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
	... 6 more

![20210221_213134](https://user-images.githubusercontent.com/38558911/108678097-f23a2c00-74ea-11eb-97b7-f4573dd72014.jpg)

**Comment by Alemiz112** [comment]
Hello, do you use any plugins?

**Comment by Alemiz112** [comment]
If yes, it seems like your plugin is the issue. It thrown NPE at `Main.java:97`

**Comment by TobiasG-DE** [comment]
He does, the stacktrace contains "de.proxyutils". This is a plugin-related issue caused by your handler for the Login event. If you need help with the issue feel free to head over to our discord server.
