### ISSUE TITLE
PLUGINS ERRO

### ISSUE THREAD

**Issue by ImHammer** [WaterdogPE/WaterdogPE#87]
All plug-ins have this error, although everything is correct.

 Error while loading plugin main class(main=dev.waterdog.examples.RandomServerJoin,plugin=RandomServerJoin)
java.lang.ClassNotFoundException: dev.waterdog.examples.RandomServerJoin
	at dev.waterdog.plugin.PluginClassLoader.findClass(PluginClassLoader.java:46) ~[server.jar:?]
	at dev.waterdog.plugin.PluginClassLoader.findClass(PluginClassLoader.java:41) ~[server.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at dev.waterdog.plugin.PluginLoader.loadPluginJAR(PluginLoader.java:52) ~[server.jar:?]
	at dev.waterdog.plugin.PluginManager.loadPlugin(PluginManager.java:93) ~[server.jar:?]
	at java.util.TreeMap.forEach(TreeMap.java:1002) ~[?:?]
	at dev.waterdog.plugin.PluginManager.loadPluginsIn(PluginManager.java:70) ~[server.jar:?]
	at dev.waterdog.plugin.PluginManager.<init>(PluginManager.java:44) ~[server.jar:?]
	at dev.waterdog.ProxyServer.<init>(ProxyServer.java:122) ~[server.jar:?]
	at dev.waterdog.WaterdogPE.main(WaterdogPE.java:54) ~[server.jar:?

**Comment by Alemiz112** [comment]
You have probably compiled the plugin incorrectly.

**Comment by ImHammer** [comment]
I used (mvn clean install) inside the plugin folder

**Comment by Alemiz112** [comment]
Pull request #89 should fix it.

**Comment by Alemiz112** [comment]
Fixed in latest build. @TobiasG-DE now needs to update Example Plugins to make it work correctly.
